### ISSUE TITLE
请问一下卡图来源

### ISSUE THREAD

**Issue by kooriookami** [Koolercat/ygo-card-pic#1]
你好，请问卡图有什么脚本获取吗，方便分享一下吗~

**Comment by Koolercat** [comment]
大佬你别问我啊😂，这就是当时看了你的游戏王卡片生成器项目，然后从ygoprodeck里批量下载了一批卡图，甚至后来我都把这个给忘了。现在ygoprodeck是改版了是吗？不能用了？

**Comment by kooriookami** [comment]
现在ygoprodeck的卡图压缩了，没有你库里的清晰，那估计没了哈哈
